project_id = "moirryvajzyriagqihbe"

[functions.get-pending-activities]
verify_jwt = false

[functions.analyze-resume]
verify_jwt = false

[functions.redefine-resume]
verify_jwt = false

[functions.get-subscription-plans]
verify_jwt = false

[functions.search-jobs-api]
verify_jwt = false

[functions.auto-assign-section-assignments]
verify_jwt = false

[functions.verify-institute-assignments]
verify_jwt = true

[functions.initialize-job-hunting-week]
verify_jwt = true

[functions.daily-progress-capture]
verify_jwt = false

[functions.razorpay-verify-payment]
verify_jwt = false

[functions.user-signup-webhook]
verify_jwt = false

[functions.process-webhook-queue]
verify_jwt = false

[functions.test-webhook]
verify_jwt = false

[functions.sync-user-profiles]
verify_jwt = false

[functions.test-payment-insert]
verify_jwt = false

[functions.instamojo-webhook]
verify_jwt = false

[functions.test-instamojo]
verify_jwt = false

[functions.instamojo-create-order-debug]
verify_jwt = false

[functions.interview-coach-chat]
verify_jwt = true

[functions.assignment-evaluator-chat]
verify_jwt = true

[functions.voice-to-text]
verify_jwt = true

[functions.coding-copilot-chat]
verify_jwt = true

[functions.aws-certs-chat]
verify_jwt = true

[functions.aws-certs-assistant]
verify_jwt = true

[functions.text-to-speech]
verify_jwt = true

[functions.ai-assistant]
verify_jwt = true

[functions.parse-resume]
verify_jwt = false

[functions.get-resume-status]
verify_jwt = false

[functions.get-skills-status]
verify_jwt = false

[functions.get-job-status]
verify_jwt = false

[functions.scrape-job-details]
verify_jwt = false

[functions.fetch-job-with-gemini]
verify_jwt = false

[functions.job-search]
verify_jwt = false