-- Phase 1C: Insert notification templates
INSERT INTO public.notification_templates (template_key, title_template, message_template, email_subject_template, email_body_template, category) VALUES
('job_application_reminder', 'Job Application Reminder', 'It''s been a while since your last job application. Keep up the momentum!', 'Time to Apply for New Opportunities', 'Hi {{user_name}}, it''s been a while since your last job application. Keep up the momentum and apply to new opportunities today!', 'job_hunting'),
('new_job_posted', 'New Job Posted', 'A new job opportunity "{{job_title}}" at {{company}} has been posted!', 'New Job Opportunity: {{job_title}}', 'Hi {{user_name}}, a new job opportunity "{{job_title}}" at {{company}} has been posted that matches your profile!', 'job_hunting'),
('assignment_due_soon', 'Assignment Due Soon', 'Your assignment "{{assignment_title}}" is due in {{days}} days', 'Assignment Reminder: {{assignment_title}}', 'Hi {{user_name}}, your assignment "{{assignment_title}}" is due in {{days}} days. Don''t forget to submit it on time!', 'assignments'),
('assignment_completed', 'Assignment Completed', 'Congratulations! You''ve completed "{{assignment_title}}" and earned {{points}} points', 'Assignment Completed Successfully', 'Congratulations {{user_name}}! You''ve successfully completed "{{assignment_title}}" and earned {{points}} points.', 'assignments'),
('subscription_expiring', 'Subscription Expiring Soon', 'Your {{plan_name}} subscription expires in {{days}} days', 'Subscription Renewal Reminder', 'Hi {{user_name}}, your {{plan_name}} subscription expires in {{days}} days. Renew now to continue enjoying all features.', 'subscription'),
('points_milestone', 'Points Milestone Achieved', 'Congratulations! You''ve reached {{points}} points', 'You''ve Reached a New Milestone!', 'Congratulations {{user_name}}! You''ve reached {{points}} points. Keep up the great work!', 'achievements'),
('follow_up_reminder', 'Follow-up Reminder', 'Time to follow up on your application for {{job_title}} at {{company}}', 'Follow-up Time: {{job_title}}', 'Hi {{user_name}}, it''s time to follow up on your application for {{job_title}} at {{company}}. A timely follow-up can make all the difference!', 'job_hunting'),
('github_streak_achieved', 'GitHub Streak Achieved', 'Amazing! You''ve maintained a {{days}} day GitHub commit streak', 'GitHub Streak: {{days}} Days!', 'Amazing work {{user_name}}! You''ve maintained a {{days}} day GitHub commit streak. Keep coding!', 'technical'),
('linkedin_milestone', 'LinkedIn Network Milestone', 'Great job! You now have {{connections}} LinkedIn connections', 'LinkedIn Network Growing: {{connections}} Connections', 'Great networking {{user_name}}! You now have {{connections}} LinkedIn connections. Your professional network is growing!', 'networking'),
('profile_completion_reminder', 'Complete Your Profile', 'Your profile is only {{percentage}}% complete. Complete it to improve your job search success!', 'Complete Your Profile for Better Opportunities', 'Hi {{user_name}}, your profile is only {{percentage}}% complete. Complete it to improve your job search success and attract more opportunities!', 'profile')
ON CONFLICT (template_key) DO NOTHING;